### PR TITLE
Proposal: update skip-list

### PR DESCRIPTION
**Pull request by tsuyoshicho**
Proposal update skip-list.

- add Git(and hub command) any other special files.
- add vim famous plugin special files

### CODE REVIEW

**Comment by mhinz** [comment]
I would argue that any file from `.git` should be listed. How about this?

```diff
diff --git i/autoload/startify.vim w/autoload/startify.vim
index fa65268..52c29b8 100644
--- i/autoload/startify.vim
+++ w/autoload/startify.vim
@@ -1094,7 +1094,7 @@ let s:tf = exists('g:startify_transformations')
 let s:session_dir = s:get_session_path()

 let s:skiplist = get(g:, 'startify_skiplist', [
-      \ 'COMMIT_EDITMSG',
+      \ '\.git/.*',
       \ 'runtime/doc/.*\.txt',
       \ 'bundle/.*/doc/.*\.txt',
       \ 'plugged/.*/doc/.*\.txt',
```

**Comment by tsuyoshicho** [comment]
I don't have any material to judge whether everything under .git is in scope, so I think it's still good.

---

Ah... `fugitiveblame` use in [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive) Gblame mode.
It is OK?

**Comment by mhinz** [comment]
Ah, I never noticed that `fugitiveblame` files would be listed as well, because these files get deleted on exiting Vim, so Startify will only list them if you use `:Startify` together with `let g:startify_update_oldfiles = 1`, right?

Okay, so, please change the commit to:

```diff
diff --git i/autoload/startify.vim w/autoload/startify.vim
index fa65268..23ecdd0 100644
--- i/autoload/startify.vim
+++ w/autoload/startify.vim
@@ -1094,10 +1094,11 @@ let s:tf = exists('g:startify_transformations')
 let s:session_dir = s:get_session_path()

 let s:skiplist = get(g:, 'startify_skiplist', [
-      \ 'COMMIT_EDITMSG',
       \ 'runtime/doc/.*\.txt',
       \ 'bundle/.*/doc/.*\.txt',
       \ 'plugged/.*/doc/.*\.txt',
+      \ '/.git/',
+      \ 'fugitiveblame$',
       \ escape(fnamemodify(resolve($VIMRUNTIME), ':p'), '\') .'doc/.*\.txt',
       \ ])

```

**Comment by tsuyoshicho** [comment]
Okay and Thanks option information.

**Comment by mhinz** [comment]
Thanks! ✨ 

(I changed it again so that `escape(fnamemodify(resolve(...)))` comes last, because it's the potentially slowest operation.)

**Comment by tsuyoshicho** [comment]
Thanks and Last OK.

**Pull request merged**
