### PR TITLE
Removed parentheses around devicons

### PR DESCRIPTION
**Pull request by zeorin**
Perhaps it's just me, but those parentheses look weird. I've removed them.
I think it looks better.

screenshot from 2016-04-22 11-12-12

### CODE REVIEW

**Comment by letientai299** [comment]
Hi @zeorin, I think It's would be better if you make this an option, instead of force all users to remove the parentheses. Some one may prefer the current style.

**Comment by zeorin** [comment]
OK, I'll work on that.

**Comment by mhinz** [comment]
Actually I once attempted to make the whole entry format public as an option. It worked, but lead to more chaos than good.

Anyway, I don't use devicons, but agree that it looks neat this way. Merged!

**Comment by zeorin** [comment]
Thanks for merging. There's a lot users can do with syntax highlighting anyway. Here's how mine looks now:
screenshot from 2016-06-01 16-29-15

**Pull request closed without merging**
